version: '3'
services:
  inferno:
    build:
      context: ./
      dockerfile: Dockerfile.development
    volumes:
      - ./:/opt/inferno
    ports:
      - target: 4567
        published: 4567
        mode: host
    environment:
      - VALIDATOR_URL=http://validator_service/validatorapi
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - validator_service
      - nginx
      - redis
  validator_service:
    extends:
      file: docker-compose.background.yml
      service: validator_service
  fhir_validator_app:
    extends:
      file: docker-compose.background.yml
      service: fhir_validator_app
  nginx:
    extends:
      file: docker-compose.background.yml
      service: nginx
  redis:
    extends:
      file: docker-compose.background.yml
      service: redis
